name: transformersum
channels:
    - conda-forge
    - pytorch
dependencies:
    - pytorch
    - scikit-learn
    - tensorboard
    - spacy
    - sphinx
    - pyarrow
    - pre-commit
    - pip
    - python==3.10
    - pip:
      - pytorch-lightning==1.6.5
      - transformers
      - torch_optimizer
      - wandb
      - rouge-score
      - packaging
      - datasets
      - gradio
